version: "3.5"
services:
  db:
    container_name: sql_server
    image: mcr.microsoft.com/mssql/server
    restart: always
    environment:
      - SA_PASSWORD=Password1
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file:
      - .testing.env
    depends_on: 
      - db
      - mongo
    command:
      [
        "./Scripts/wait-for-it.sh",
        "mongo:27017",
        "-t",
        "120",
        "--",
        "./Scripts/start-tests.sh"
      ]
